:py:mod:`nautobot_device_onboarding.exceptions`
===============================================

.. py:module:: nautobot_device_onboarding.exceptions

.. autoapi-nested-parse::

   Exceptions.

   (c) 2020-2021 Network To Code
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.



Module Contents
---------------

.. py:exception:: OnboardException(reason, message, **kwargs)

   Bases: :py:obj:`Exception`

   A failure occurred during the onboarding process.

   The exception includes a reason "slug" as defined below as well as a humanized message.

   .. py:attribute:: REASONS
      :annotation: = ['fail-config', 'fail-connect', 'fail-execute', 'fail-login', 'fail-dns', 'fail-general']

      

   .. py:method:: __str__(self)

      Exception __str__.



